### ISSUE TITLE
mdoel

### ISSUE THREAD

**Issue by saitarunmandiga** [Zorrat/Student-Online-Exam-AntiCheat-Tool#1]
can You please share model "yolov4.h5" the google link is expired

**Comment by Pranavagrl** [comment]
hey bro can u provide the model once again

**Comment by Zorrat** [comment]
hey guys.
I have reuploaded the original model file. Here is the link
https://drive.google.com/file/d/1BpgRAA94Oh7pCjrI_VsqTtR3O-Lc2q4h/view?usp=sharing
